name: A股行情监控

on:
  schedule:
    - cron: '*/5 1-7 * * 1-5'
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4

    - name: 设置 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: 安装依赖
      run: pip install akshare requests

    - name: 运行监控脚本
      env:
        SEND_KEY: ${{ secrets.SEND_KEY }}
      run: python stock_monitor.py
